name: Generate Cypress Reports
on:
  push:
      branches:
          - main
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3.5.2

          - name: Cypress.io
            uses: cypress-io/github-action@v5.6.2

          - name: Copy test execution videos and screenshots
            run: |
                mkdir public
                cp -r cypress/videos public/videos
                cp -r cypress/screenshots public/screenshots

          - name: Merge test reports
            run: npm run combine:report

          - name: Generate HTML reports
            run: npm run generate:report

          - name: Deploy report page to Github Page
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{secrets.GITHUB_TOKEN}}
              publish_dir: ./public
           
                
                

        