name: Generate Cypress Reports
on:
  push:
      branches:
          - 'main'
jobs:
    cypress-test:
        name: Run on Chrome 83
        runs-on: ubuntu-latest
        container : cypress/browsers:node12.18.0-chrome83-ff77
        steps:
          - name: Checkout
            uses: actions/checkout@v3.5.2

          - name: Install cypress and verify
            run : |
              npm ci
              $(npm bin)/cypress verify

          - name: Run Cypress Tests
            run: npm run test:chrome
            continue-on-error: false

          - name: Copy test execution videos and screenshots
            run: |
                mkdir public
                cp -r cypress/videos public/videos
                cp -r cypress/screenshots public/screenshots

          - name: Merge test reports
            run: npm run combine:report

          - name: Generate HTML reports
            run: npm run generate:report

          - name: Deploy report page to Github Page
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{secrets.GITHUB_TOKEN}}
              publish_dir: ./public
           
                
                

        