name: Smoke Test
on:
  push:
      branches:
          - main
jobs:
  generate-report:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          env: SUITE=smoke

      - name: Generate Allure report
        if: always()
        uses: afiore/action-allure-report@v0.1.0